In [4]:
import numpy as np

In [5]:
print(np.__version__)

1.26.4


In [6]:
array = np.array([1,2,3,4])

print(array)

[1 2 3 4]


In [7]:
#double the number in array 
array = array * 2
print(array)


[2 4 6 8]


In [8]:
a = np.array('A')
print(a)
print(a.ndim)

A
0


In [9]:
b = np.array([[[1,2,3],
             [4,5,6]],
             [[22,33,44],
             [7,8,9]]])
print(b.ndim)

3


In [21]:
array = np.array( [[['a','b','c'],['d','e','f'],['g','h','i']],
                  [['j','k','l'],['m','n','o'],['p','q','r']],
                  [['s','t','u'],['v','w','x'],['y','z','_']]])
 

print(array[0][1][2]) #chain indexind 
print(array[1,2,0]) #multi- dimension indexing 

word = array[0,1,2] + array[2,0,2] + array[0,0,2] + array[1,0,1] + " " + array[2,0,2]

print(word)


f
p
fuck u


In [23]:
num = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

#ending index is exclusive - so i u want to print 3rd line write 
print(num[0:4])
print(num[2:4])
print(num[::])

print(num[::-1]) #print in reverse

print(num[1::]) #will print everything fron 1 index and it is inclusive



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Now Column selection 

In [25]:
print(num[:,0]) # array[rows, columns] 
#give me all the rows from col 0

print(num[1:3,1]) 
print(num[:,1:])
#selecting only 2nd coloumn

print(num[:,::2])
print(num[0:2,0:2])

[ 1  5  9 13]
[ 6 10]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[1 2]
 [5 6]]


## Scalar arithmetic

In [27]:
arry1 = np.array([1,2,3])

print(arry1 + 1 ) 
print(arry1 -2 )
print(arry1 * 2)
print(arry1 / 2)
print(arry1 ** 2)

[2 3 4]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]


In [29]:
arry2 = np.array([2,3,4])
rnd = np.array([2.34,4.43,6.67])

print(np.sqrt(arry2))
print(np.round(rnd))
print(np.floor(rnd))
print(np.ceil(rnd))

[1.41421356 1.73205081 2.        ]
[2. 4. 7.]
[2. 4. 6.]
[3. 5. 7.]


In [31]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2 )
print(arr1 - arr2 )
print(arr1 * arr2 )
print(arr1 / arr2 )
print(arr1 ** arr2 )

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [33]:
marks = np.array([50,68,75,98,100])

print(marks >70 )
print(marks >= 100)


[False False  True  True  True]
[False False False False  True]


In [35]:
 num1 = np.array([1,2,3,4,5,6,7,8,9,10])
 num2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(num1 * num2 )

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## Aggregate functions 

In [37]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

#print(np.sum(array))
#print(np.mean(array))
#print(np.max(array))
#print(np.min(array))
#print(np.median(array))
#print(np.std(array))

print(np.sum(array , axis = 0)) #does sum of all the column 
print(np.sum(array , axis = 1)) #does sum of all the rows 

[ 7  9 11 13 15]
[15 40]


## random numbers

In [61]:
rng = np.random.default_rng()

print(rng.integers(low = 1, high= 50 , size = 4)) #this is for 1D array 
print(rng.integers(low = 1, high= 50 , size = (4,2,3))) 



[ 6 31 21 43]
[[[ 5 30 20]
  [22 13 17]]

 [[30  2 30]
  [42 14  2]]

 [[13  7 29]
  [ 7 27 44]]

 [[31 29 49]
  [18 26 33]]]


In [77]:
#if you want to generate same result set seed = 1
rng = np.random.default_rng(seed = 1)

print(rng.integers(1,10,size = (2,3)))

[[5 5 7]
 [9 1 2]]


Uniform

In [82]:
print(np.random.uniform())

0.3504185230480755
